main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#publications
    weight: 20
  - name: News
    url: /#news
    weight: 30
  - name: Notes
    url: /notes/
    weight: 40
  - name: CV
    url: /uploads/resume.pdf
    weight: 50
